---
name: Report
about: Upload run reports
title: "[REPORT]"
labels: report
assignees: ''
body:
- type: file
  attributes:
    label: `report`
    description: Attach your report .zip
    extensions: ["zip"]
    pattern: "bb-.*-report.zip"
    required: true
---


